services:
  app_auth:
    build: .
    volumes:
      - ~/.aws:/root/.aws:ro  # Mapping keys from my local machine to the container
    environment:
      - COGNITO_USER_POOL_ID=us-east-1_5Ezbsap8a
      - COGNITO_CLIENT_ID=3v932fknrrssoebuck7shsanrm
      - AWS_REGION=us-east-1
      - PYTHONPATH=/app